apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o2b98qgri-nodejs
  janus-idp.io/tekton: o2b98qgri-nodejs
  backstage.io/kubernetes-id: o2b98qgri-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o2b98qgri-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
